### Get all users
GET http://localhost:8081/users

### Create a user
POST http://localhost:8081/users
Content-Type: application/json

{
    "firstName": "Jack",
    "lastName": "Progy",
    "username": "jack",
    "profilePicture": "img.png",
    "emailAddress": "jack@gmail.com",
    "password": "987654321"
}

### Get a single user
GET http://localhost:8081/users/thanos

### Update user information
PATCH http://localhost:8081/users/thanos
Content-Type: application/json

{
    "firstName": "jackton",
    "newUserName": "thanos",
    "newEmailAddress": "thanos@yahoo.com"
}

### Delete user
DELETE http://localhost:8081/users/elton_john

### Login a user
POST http://localhost:8081/users/auth/login
Content-Type: application/json

{
    "emailAddress": "jack@gmail.com",
    "password": "987654321"
}



### ARTICLES API TESTING

### get all articles
GET http://localhost:8081/articles

### create an article
POST http://localhost:8081/articles
Content-Type: application/json

{
    "title": "how to write a linked list in Ruby",
    "description": "in this article, we see how we can write an efficient linked list in ruby",
    "article_image": "https://firebase.google.com/img.png",
    "text": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
    "author": "do@gmail.com"
}

### get a specific article
GET http://localhost:8081/articles/64acc1e8c4e6e2b32ca70348

### update an article
PATCH http://localhost:8081/articles/64acc7e5f914ed2f08c62c77
Content-Type: application/json

{
    "title": "how to write a linked list in Rust"
}

### delete an article
DELETE http://localhost:8081/articles/64acc27d7730f26e58574df6